language: node_js
matrix:
 include:
   - node_js: "stable"
     env: GULP_TASK="server-tests"
   - node_js: "0.10"
     env: GULP_TASK="server-tests"
   - node_js: "0.10"
     env: GULP_TASK="client-tests-travis"
 fast_finish: true

notifications:
 email: false
